### ISSUE TITLE
Preparse TODO for PR #145

### ISSUE THREAD

**Issue by krisselden** [emberjs/emberjs-build#167]
PR #145 TODO
- [ ] Build graph during module compilation
- [ ] Lint graph for strong connected components that have module scope side effects (fix the current issue between ember-metal and ember-debug).
- [ ] Update loader to support eager modules instead of replacing the loader
- [ ] Replace concat step instead of post-processing

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is unused by Ember and unmaintained.

Closing...
